name: utils_plus
description: "Flutter package that provides a collection of useful extensions for common Dart and Flutter types. It aims to simplify and enhance your development experience by offering convenient methods and utilities."
version: 0.0.1
homepage: https://neupanenitesh.com.np/utils_plus
repository: https://github.com/niteshneupane/utils_plus
issue_tracker: https://github.com/niteshneupane/utils_plus/issues
documentation: https://neupanenitesh.com.np/utils_plus/docs

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: Utils Table Home Page 1
    path: screenshots/1.jpg
  
  - description: Utils Table Home Page 2
    path: screenshots/2.jpg
